var soupArray = ["Roasted Plum Tomoato \n& Basil", "Pea & Ham", "Curried Parsnip", "Leek & Potato", "Spiced Carrot \n& Red Lentil Broth", "Mushroom", "Broccoli & Stilton", "Tomato & Basil", "Pea & Mint", "Potato & Truffle", "Sweet Potato \n& Rosemary", "Roasted Plum Tomato \n& Red Pepper", "Garden Pea \n& Spinach", "Cauliflower & Cheddar", "Asian Chicken \n& Noodles", "Parsnip & Apple", "Minestrone", "Spinach & Confit Garlic", "Forest Mushroom \n& White Truffle", "Baby Corn & \nNoodle Miso", "Cream of Cauliflower with \nParmesan Croutes", "Brocolli & Cropwell Bishop Stilton", "Asian Chicken & Sweetcorn \nBroth"];

var meatArray = ["Basil Pesto Chicken Supreme \nwith Parmesan Shavings & Toasted Pinenuts", "Individual Cottage Pie topped \nwith Thomas Hoe Red Leicester", "Crispy Sweet & Sour Pork \nwith Pineapple & Egg Fried Rice", "Lamb Moussaka with \nAubergine & Ricotta", "Salmon en Route \nwith Dill Veloute", "Beef Meatballs in rich \ntomato sauce wtih spaghetti", "Thyme, ale and honey glazed \nPork shoulder with \nblack pudding", "Hot Salt Beef on Rye \nbread with mustard & Pickle", "Chicken Kiev with \nGarlic and herb butter", "Salmon en Croute", "Chargrilled Chicken Supreme with \na creamy red pepper sauce", "Fruity Lamb Tagine \nwith Apricots & Dates", "Glazed Pork Belly with \nApple chutney & crisp crackling", "Chicken Fricassee with \nleeks & oyster mushrooms", "Salmon en croute with \nbeurre blanc", "Goldern Katsu Chicken with \nCurry Sauce & Pak Choi", "Pan fried Calves Liver with \nCandied Bacon & Onion Gravy", "Massaman Duck & Lycee Curry \nwith Kaffir Lime Leaves", "Breaded Turkey filled with \nBrie, Sage & Cranberries", "Panko Breaded Chicken \nBreast with Emmental & \nHickory Smoked BBQ Sauce", "Pan fried Calves Liver with \nRed Onion Marmarlade & Crisp Bacon", "Sage & Parmesan Crusted Pork \nChop, Wholegrain Mustard Sauce", "Chicken Vindaloo with Sambals, \nPoppadoms & Pilau Rice"];

var carveryArray = ["Roast Free Range Chicken \nwith Bread Sauce & Gravy", "Garlic & Rosemary roast \nleg of lamb with jus", "28 day matured roast rib of \nbeef with Yorkshire pudding & Jus","Honey roast gammon \nwith parsley sauce", "Bourbon Glazed Pulled Pork, Wraps, Monteray \nJack Cheese & Spiced Apples"];

var fishArray = ["Smoked Haddock Rarebit with \nSpinach & Poached Hens Egg", "Fried Red Snapper with Ginger, \nSpring Onion, Lime & Sweet Chilli Sauce", "Cod & Parsley Fishcakes \nwith Sauce Gribiche", "Catalan Fish Stew with \nChorizo & Garlic Toast", "Beer Battered haddock with \nlemon wedges & tartar sauce", "Cajun red mullet with \ngrilled peppers and onion", "Fish Pie", "Lemon garlic and parsley \nbaked Whiting", "Pan fried sea bream \nwith ginger, soy & spring onion", "Abroath haddock smokies topped with \n a poached egg & \nhollandaise sauce", "Pan fried seabass with \npuy lentils & red wine jus", "Cajun spiced salmon fillet with \nroasted cherry tomotoes & miny yoghurt", "Thai fishcakes with \ncucumber dipping sauce", "Traditional Fish Pie with Smoked \nHaddock, Prawns & Salmon", "Grilled Cajun Swordfish Steak with \nRed Pepper Gremolata \n& Grilled Lemon", "Steamed Paupiettes of Plaice filled \nwith a Hot Smoked Salmon \n&Crab mousse, Champagne Sauce", "Pan Fried Mackrel with a \nCaponata Dressing & Braised Chicory", "Roasted Hake with Asparagus \n& White Wine Fish Sauce", "Crisp Skin Seabass with \na Pea & Mint Salsa", "Lemongrass & Ginger Crab Cakes \nwith Sweet Chilli & Lime"];

var vegetarianArray = ["Fired Mushroom Burgers with \nCaramelised onions & Roasted Garlic Mayonnaise", "Pumpkin & Mozzarella Arrancini", "Tomato Ragout", "Stuffed Peppers with \nPearl Barley & Feta", "Quornish Pasties \nwith Onion Gravy", "Pea, Mint & Lemon Risotto", "Shallot tartlet with \ngoat cheese and rocket", "Butternut squash, red onion \nand feta frittata", "Chilli 'Quorn' carne with \nsour cream and salsa", "Mixed Vegetables madras \ncurry with popadoms", "Oriental quorn chow mein \nwith soy noodles & sweet chilli", "Pumpkin & Parmesan risotto \nwith micro basil", "Spiced Aubergine Pie", "Cauliflower & Potato Curry \nwith poppadoms & Naan", "Stuffed Peppers with \nspiced rice", "Goldern Beetroot, Sorrel & Widnrush \nGoats Cheese Tart", "Broad Bean, Leek & Courgette \nFrittata, Balsamic Caramel", "Grilled Haloumi, Heritage Tomoato & Red \nPepper Brochettes serverd with \nPistou & Rocket Salad", "Spiced Falafels with Grilled \nFlatbreads, Babaghanoush \n& Spiced Yoghurt", "Butternut Squash & Spinach \nRisotto topped with Toasted Seeds", "Spanish Tortilla with a Red \nPepper Coulis & Rocket Salad", "Goats Cheese, Pear & \nChice Quiche", "Lentil Hot Pot with \nHerb Dumplings", "Baked Aubergine Filled with \nPepponata & Mozzarella", "Beetroot & Chickpea Fritters \nwith a Safron Yoghurt"];

var potatoesArray = ["Sauté New Potatoes", "Roast Potatoes", "Chunky Chips", "Sweet Potato Wedges", "Boulangere", "New Potatoes", "Creamy Mash", "Lyonnaise Potato", "Braised Rice", "Cous Cous", "Rustic Fondant", "Garlic Mash", "Braised Rice", "Lemon Rice", "Boiled Potatoes", "Dauphinoise"];

var vegetablesArray = ["French Beans", "Vichy Carrots", "Warm Bean Salad", "Braised Peas", "Savoy Cabbage", "Cauliflower Cheese", "Sauté Mange Tout", "Roasted Med Veg", "Buttered Sweetcorn", "Roasted Roots", "Broccoli", "Braised Red Cabbage", "Garden & Mushy Peas", "Baked Beans", "Vegetable Medley", "Crushed Celeriac", "Braised Leeks", "Cauliflower", "Grilled corn on the cob, roasted sweet potato and squash", "Roasted Carrot & Parsnips", "Slow roasted plum tomatoes", "Peas", "Wilted Sweetheart Cabbage", "Peas with Feta \n& Mint", "Baked Sweet Potato \n& Red Onion", "Courgettes with Lemon", "Steamed Brocolli", "Rustic Carrots", "Sweetcorn With Baby \nOnions", "Sugar Snaps", "Peas with Cherry Tomatoes \n& Baby Gem", "Sauté Courgettes", "Cauliflower with a Herb \n& Quinoa Crust", "French Beans with \nCrispy Shallots", "Garlic Portabello Mushrooms", "Garden Mushy Peas", "Baked Field Mushrooms", "Braised Leeks", "Maple Glazed Carrots", "Ratatouille", "Spring Greens", ];